title: Fun With Visual Studio
email: blog@johnkoerner.com
description: > # Having fun hacking on Visual Studio and its related tooling.
url: "https://johnkoerner.com" # the base hostname & protocol for your site
twitter_username: johnkoerner
github_username:  johnkoerner
stackoverflow_link: users/573218/john-koerner
# Build settings
markdown: kramdown
kramdown:
  input: GFM
  parse_block_html: true
  #parse_span_html: true
#theme: minima
permalink:     /:categories/:title/

disqus: johnkoernersblog
google_analytics_ua: UA-55411926-1

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md